version: "3"
services:
  db:
    image: postgres:14
    ports:
      - "5433"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_SERVER=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8001:8001"
    volumes:
      - ./backend/app:/app
      - ./backend/assets:/assets
    environment:
      - DATABASE_URL=postgresql://db
      - BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
volumes:
  app-db-data:
