[tool.poetry]
name = "app"
version = "0.0.1"
description = "Ultimate FastAPI Tutorial Part 2"
authors = ["ChristopherGS"]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
uvicorn = "~0.11.3"
fastapi = "^0.104.0"
python-multipart = "~0.0.5"
pydantic = {extras = ["email"], version = ">=1.10"}
